apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: springpetclinic
  name: spring-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: springpetclinic
    spec:
      containers:
      - image: mjaballi/spring-petclinic
        name: springpetclinic
        ports:
        - name: springpetclinic
          containerPort: 8080     
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: springpetclinic
  name: springpetclinic
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: springpetclinic
---
# more mysql-master-rc.yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  replicas: 1
  selector:
    name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      containers:
        - name: master
          image: mysql:5.7
          ports:
            - containerPort: 3306
        #  env:
       #     - name: MYSQL_ROOT_PASSWORD
      #        value: "test"
     #       - name: MYSQL_REPLICATION_USER
    #          value: 'demo'
   #         - name: MYSQL_REPLICATION_PASSWORD
  #            value: 'demo'
          environment:
            - MYSQL_ROOT_PASSWORD=petclinic
            - MYSQL_DATABASE=petclinic
          volumes:
            - "./conf.d:/etc/mysql/conf.d:ro"              
# more mysql-master-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: mysql-master
